/** @type {import('tailwindcss').Config} */
/* AUTO-GENERATED from warm-editorial.design.md on 2026-04-26T14:11:29+00:00. Do not edit. */

export default {
  content: ['./**/*.{html,js,jsx,ts,tsx}'],
  darkMode: 'media',
  theme: {
    extend: {
      colors: {
        'primary': '#141413',
        'secondary': '#5E5D59',
        'tertiary': '#87867F',
        'neutral': '#F5F4ED',
        'surface': '#FAF9F5',
        'surface-alt': '#E8E6DC',
        'surface-dark': '#30302E',
        'brand': '#C96442',
        'brand-soft': '#D97757',
        'on-primary': '#FAF9F5',
        'on-dark': '#B0AEA5',
        'border-soft': '#F0EEE6',
        'border-warm': '#E8E6DC',
        'border-dark': '#30302E',
        'ring-warm': '#D1CFC5',
        'ring-deep': '#C2C0B6',
        'focus': '#3898EC',
        'error': '#B53333',
      },
      fontFamily: {
        'display': ['Anthropic Serif, Georgia, serif', 'serif'],
        'body': ['Anthropic Sans, Inter, system-ui, sans-serif', 'serif'],
        'body-2': ['Anthropic Mono, SFMono-Regular, Consolas, monospace', 'monospace'],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '1.1', letterSpacing: '0', fontWeight: '500' }],
        'headline-xl': ['52px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '500' }],
        'headline-lg': ['36px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.1', letterSpacing: '0', fontWeight: '500' }],
        'headline-sm': ['25px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '500' }],
        'feature-title': ['21px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '500' }],
        'body-serif': ['17px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-lg': ['20px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['15px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'caption': ['14px', { lineHeight: '1.43', letterSpacing: '0', fontWeight: '400' }],
        'label': ['12px', { lineHeight: '1.25', letterSpacing: '0.12px', fontWeight: '500' }],
        'overline': ['10px', { lineHeight: '1.6', letterSpacing: '0.5px', fontWeight: '400' }],
        'code': ['15px', { lineHeight: '1.6', letterSpacing: '-0.32px', fontWeight: '400' }],
      },
      borderRadius: {
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '24px',
        '3xl': '32px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '24px',
        '2xl': '32px',
        '3xl': '48px',
        '4xl': '80px',
        '5xl': '120px',
        'section': '96px',
        'pad-button': '12px',
      },
      boxShadow: {
        'ring-warm': '0 0 0 1px #D1CFC5',
        'ring-deep': '0 0 0 1px #C2C0B6',
        'whisper': '0 4px 24px rgba(0, 0, 0, 0.05)',
        'ring-soft': '0 0 0 1px rgba(201, 197, 184, 0.7)',
        'soft': '0 18px 60px rgba(20, 20, 19, 0.08)',
      },
    },
  },
};
